language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - cd backend/
  - pip install .
  - cd RayTracing/Tests
# command to run tests
script: 
  - python test_model.py
  - python test_jsonparser.py
  - python test_performance.py
