language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - cd backend/RayTracing/Tests
  - pip install .
# command to run tests
script: 
  - python test_model.py
