var arrayListForLight 		 = [];
var arrayListForObject 		 = [];
var paintOrder               = [];
var windowSize               = [];
var receivedImage            = [];
var lightClicked 			 = false;
var shapeClicked			 = false;
var settingsClicked  		 = false;
var currentView 			 = "front";
var convertSize;
var globalImagePlaneSizeObject;
var globalCameraPositionObject;
var globalCameraDirectionObject;
var globalCameraAngleObject;
var globalCameraObject;
var globalSceneObject;
var globalRaytracerObject;
var globalAmbientLight;
var globalFloor;
var globalRoom;
var globalAntialiasingObject;
var globalItem;
var globalFileName;